# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: local
      hooks:
          - id: lint-fix
            name: lint-fix
            entry: "nx affected:lint --base=master --outputStyle=stream --no-color"
            language: unsupported
            types_or: [javascript, jsx, ts, tsx]
            # require_serial: true
            verbose: true
            pass_filenames: false
